import { type NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const airport = searchParams.get("airport")

    // Airport-specific flights data
    const airportFlights = {
      Riyadh: [
        {
          flightNumber: "SV123",
          origin: "Dubai",
          gate: "A12",
          gpuActivated: true,
          acuActivated: false,
          scheduledTime: "08:30",
          status: "boarding",
          airport: "Riyadh",
        },
        {
          flightNumber: "MS456",
          origin: "Cairo",
          gate: "B05",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "09:15",
          status: "scheduled",
          airport: "Riyadh",
        },
        {
          flightNumber: "EK789",
          origin: "London",
          gate: "C08",
          gpuActivated: true,
          acuActivated: true,
          scheduledTime: "10:45",
          status: "departed",
          airport: "Riyadh",
        },
        {
          flightNumber: "QR321",
          origin: "Doha",
          gate: "A15",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "11:20",
          status: "scheduled",
          airport: "Riyadh",
        },
        {
          flightNumber: "TK654",
          origin: "Istanbul",
          gate: "B12",
          gpuActivated: true,
          acuActivated: true,
          scheduledTime: "12:30",
          status: "boarding",
          airport: "Riyadh",
        },
        {
          flightNumber: "LH987",
          origin: "Frankfurt",
          gate: "C03",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "13:45",
          status: "scheduled",
          airport: "Riyadh",
        },
      ],
      Jeddah: [
        {
          flightNumber: "SV234",
          origin: "Istanbul",
          gate: "A01",
          gpuActivated: true,
          acuActivated: true,
          scheduledTime: "07:45",
          status: "boarding",
          airport: "Jeddah",
        },
        {
          flightNumber: "TK654",
          origin: "Frankfurt",
          gate: "A04",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "08:30",
          status: "scheduled",
          airport: "Jeddah",
        },
        {
          flightNumber: "LH987",
          origin: "Munich",
          gate: "B02",
          gpuActivated: true,
          acuActivated: false,
          scheduledTime: "09:15",
          status: "scheduled",
          airport: "Jeddah",
        },
        {
          flightNumber: "BA567",
          origin: "London",
          gate: "B04",
          gpuActivated: false,
          acuActivated: true,
          scheduledTime: "10:20",
          status: "boarding",
          airport: "Jeddah",
        },
        {
          flightNumber: "AF123",
          origin: "Paris",
          gate: "B07",
          gpuActivated: true,
          acuActivated: true,
          scheduledTime: "11:45",
          status: "scheduled",
          airport: "Jeddah",
        },
        {
          flightNumber: "EK456",
          origin: "Dubai",
          gate: "C03",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "12:30",
          status: "scheduled",
          airport: "Jeddah",
        },
        {
          flightNumber: "QR789",
          origin: "Doha",
          gate: "C06",
          gpuActivated: true,
          acuActivated: false,
          scheduledTime: "13:15",
          status: "boarding",
          airport: "Jeddah",
        },
        {
          flightNumber: "MS345",
          origin: "Cairo",
          gate: "A07",
          gpuActivated: false,
          acuActivated: true,
          scheduledTime: "14:00",
          status: "scheduled",
          airport: "Jeddah",
        },
        {
          flightNumber: "KL567",
          origin: "Amsterdam",
          gate: "B01",
          gpuActivated: true,
          acuActivated: true,
          scheduledTime: "15:30",
          status: "scheduled",
          airport: "Jeddah",
        },
      ],
      Dammam: [
        {
          flightNumber: "SV345",
          origin: "Kuwait",
          gate: "A01",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "08:00",
          status: "scheduled",
          airport: "Dammam",
        },
        {
          flightNumber: "EY456",
          origin: "Abu Dhabi",
          gate: "A02",
          gpuActivated: true,
          acuActivated: true,
          scheduledTime: "09:20",
          status: "boarding",
          airport: "Dammam",
        },
        {
          flightNumber: "QR789",
          origin: "Doha",
          gate: "A05",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "10:15",
          status: "scheduled",
          airport: "Dammam",
        },
        {
          flightNumber: "KU567",
          origin: "Kuwait",
          gate: "B01",
          gpuActivated: true,
          acuActivated: false,
          scheduledTime: "11:30",
          status: "boarding",
          airport: "Dammam",
        },
        {
          flightNumber: "LH987",
          origin: "Frankfurt",
          gate: "B04",
          gpuActivated: false,
          acuActivated: true,
          scheduledTime: "12:45",
          status: "scheduled",
          airport: "Dammam",
        },
        {
          flightNumber: "MS234",
          origin: "Cairo",
          gate: "C01",
          gpuActivated: true,
          acuActivated: true,
          scheduledTime: "13:20",
          status: "departed",
          airport: "Dammam",
        },
        {
          flightNumber: "TK456",
          origin: "Istanbul",
          gate: "C06",
          gpuActivated: false,
          acuActivated: false,
          scheduledTime: "14:10",
          status: "scheduled",
          airport: "Dammam",
        },
        {
          flightNumber: "EK234",
          origin: "Dubai",
          gate: "A07",
          gpuActivated: true,
          acuActivated: false,
          scheduledTime: "15:00",
          status: "scheduled",
          airport: "Dammam",
        },
      ],
    }

    const flights = airportFlights[airport as keyof typeof airportFlights] || []

    return NextResponse.json({
      flights,
      airport,
      timestamp: new Date().toISOString(),
    })
  } catch (error) {
    return NextResponse.json({ error: "Failed to fetch flights timeline" }, { status: 500 })
  }
}
